### ISSUE TITLE
is it a bug or i'v been careless about question

### ISSUE THREAD

**Issue by Mobin-khorushi** [ikokkari/PythonProblems#1]
ARGUMENTS: [1, 2, 3]
EXPECTED: False
RETURNED: True

This is for the problem with function -> is_ascending(items)

The question is Ascending list

Well if its not ascending then what is it ?

**Comment by ikokkari** [comment]
Most likely your is_ascending function mutates the contents of the items list and returns the wrong answer, causing the discrepancy report to print out the modified items instead of the original argument.
