### ISSUE TITLE
Issue with All Branches Lead to Rome

### ISSUE THREAD

**Issue by Ridge-Bandeen** [ikokkari/PythonProblems#2]
In the instructions for this question, a strict ban on entering tabu lattice grid locations exists. The objective it to get to location (0, 0). Therefore, if (0, 0) is included in the tabu location list, entering it should be impossible (return 0).

Instead, because of the order of returns given in the suggested solution, the tester allows the program to move into this space even when it is on the tabu list. At least one test case gave me a "wrong solution" for returning 0 when (0, 0) was on the tabu list.

Note: Please do not fix this before grading my assignment! I'm handing it in now, and it passes the tests at they exist at this point in time.

**Comment by ikokkari** [comment]
Hello,

Yes, I will certainly take a look at that next. Thank you for informing me.

Ilkka Kokkarinen

**Comment by ikokkari** [comment]
I will also ask Jimmy or Riyad, whichever is your teacher, to give you two bonus points for the labs for finding this bug.
