### ISSUE TITLE
`is_left_handed` is tested with lists, not tuples as described in the problem sheet

### ISSUE THREAD

**Issue by dovecode** [ikokkari/PythonProblems#5]
The problem sheet for problem 15, "Chirality", specifies that (emphasis mine):

> Given the **three-tuple** of `pips` read clockwise around some corner, determine whether that die is left-handed

However, the test script will not call the method `is_left_handed` with a three-tuple. Instead it uses three-element lists.

**Comment by ikokkari** [comment]
You are absolutely right. Thank you for catching this one. Next time that I post the latest update to the problem spec, I will have this issue corrected in that update. Thank you again.

**Comment by ikokkari** [comment]
Updated the 109 Python Problems spec accordingly.
